version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y awscli jq
      - echo "Install complete."

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=us-east-1
      - REPOSITORY_NAME= mind-app
      - IMAGE_TAG=$(date +%Y%m%d%H%M)
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - echo "Pre-build completed."

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_NAME .
      - docker tag $REPOSITORY_NAME:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG
      - echo "Docker build completed."

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG
      - echo "Creating imagedefinitions.json for CodeDeploy/ECS..."
      - printf '[{"name":"devops-app","imageUri":"%s"}]' $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG > imagedefinitions.json
      - echo "Build completed successfully."

artifacts:
  files:
    - imagedefinitions.json
    - deployment.yaml
    - service.yaml
