version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/mind-app
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 90

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180

  ValidateService:
    - location: scripts/validate.sh
      timeout: 30
